# Linux:
LIBS=-lvga -lm
OUT=test2
# DOS:
#LIBS=
#OUT=test2.exe

default:
	gcc -Wall -g test2.c -o $(OUT) -I../include -L../lib -lair -lquick -lflash -lmetal -lwood -lcrash -ldrwily $(LIBS)

clean:
	rm -f test2 test2.exe
